name: Build and Deploy
on:
  push:
    paths:
      - 'src/*'
      - '*.json'
      - '*.js'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop
        BRANCH: master
        FOLDER: dist/alinstefanolaru
        BUILD_SCRIPT: npm install && npm run-script build
        CNAME: alinstefanola.ru
